### ISSUE TITLE
Buffer is not defined in browser (Chrome) environment

### ISSUE THREAD

**Issue by arbesfeld** [benjamn/arson#1]
I'm trying to use Arson in Chrome (50.0.2661.94) and getting an error `ReferenceError: Buffer is not defined` when trying to stringify.

It seems that this line: https://github.com/benjamn/arson/blob/f9d522a37abb5efcd45f18191d21ce2e15e7531f/custom.js#L11 assumes the presence of `Buffer`.

Not sure how to go about fixing this, since obviously a Buffer that is `stringified` in Node.js must have a different structure in the browser.

**Comment by benjamn** [comment]
We should definitely be checking if `Buffer` is defined, like we do for [`Set`](https://github.com/benjamn/arson/blob/f9d522a37abb5efcd45f18191d21ce2e15e7531f/custom.js#L63-L65) and `Map`.

**Comment by benjamn** [comment]
Feel free to reopen if that didn't fix it, of course!
